# Generated by Django 3.2 on 2021-05-06 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Открыто'), (2, 'Выполняется'), (3, 'Закрыто')], default=1, verbose_name='Статус'),
        ),
    ]
